export const ROUTES = {
	overview: "/",
	calender: "/calender",
	rentals: "/rentals",
	leasing: "/leasing",
	people: "/people",
	taskAndMaintenance: "/task-and-maintenance",
	accounting: "/accounting",
	communication: {
		index: "/communication",
		announcements: "/communication/announcements",
		communicationLogs: "/communication/communication-logs",
		signatureRequests: "/communication/signature-requests",
		signatureTemplates: "/communication/signature-templates",
	},
	notes: "/notes",
	files: "/files",
	reports: "/reports",
	notifications: "/notifications",
	getStarted: "/get-started",
	help: "/help",
	settings: {
		index: "/settings",
		personalInformation: "/settings/personal-information",
	},
};
